db:
  type: 'mysql'
  host: '119.91.208.237'
  port: 3306
  username: 'ww_test'
  password: 'ww1157606081'
  database: 'ww_test'
  synchronize: true
  autoLoadEntities: true
  
redis:
  host: '119.91.208.237'
  port: 6379
  password: 'ww1157606081'
  db: 0

upload:
  path: 'D:/360MoveData/Users/王威/Desktop/公司项目/nest-upload'
    
  